name: Build Docker Container & Push to Cloud

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ master ]

# Define environment variables for the workflow
env:
  REPOSITORY: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  # Run frontend tests using the test-frontend.yaml workflow
  test_frontend:
    uses: ./.github/workflows/test-frontend.yaml
  # Build and deploy the Docker container
  docker_build:
    runs-on: ubuntu-latest
    # Ensure tests pass before building
    needs: [ test_frontend ]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate short SHA for Docker image tagging
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      # Authenticate with GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Pass backend URL as a build secret
          secrets: |
            "VITE_BACKEND_URL=${{secrets.VITE_BACKEND_URL}}"
          # Tag image with both commit SHA and 'latest'
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.COMMIT_SHORT_SHA }}
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest

      # Deploy to DigitalOcean
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        with:
          app_name: 'frontend'
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
